In [7]:
import numpy as np

def dropout_forward(input_array, drop_prob):
    """
    Applies dropout to the input input_array during the forward pass.
    
    Parameters:
    input_array -- input array (numpy array of any shape)
    drop_prob -- probability of dropping a neuron (float between 0 and 1)
    
    Returns:
    out -- output array with dropout applied
    mask -- dropout mask to be used in the backward pass
    """
    
    # Step 1: Generate a matrix of random values between 0 and 1 with the same shape as x
    random_matrix = np.random.rand(*input_array.shape)
    
    # Step 2: Create the dropout mask
    # Compare the random values with the dropout probability p
    mask_boolean = random_matrix > drop_prob
    
    # Step 3: Convert the boolean mask to a float mask
    # True becomes 1.0 and False becomes 0.0
    mask_float = mask_boolean.astype(float)
    
    # Step 4: Scale the mask to maintain the expected value of the activations
    # This compensates for the dropped neurons
    mask_scaled = mask_float / (1 - drop_prob)
    
    # Step 5: Apply the mask to the input x
    out = x * mask_scaled
    
    # Return the output with dropout applied and the mask
    return out, mask_scaled

In [6]:
# Example usage
x = np.array([[0.1, 0.2, 0.3], 
              [0.4, 0.5, 0.6],
              [0.2, 0.5, 0.6],
              [0.4, 0.3, 0.6],
              [0.4, 0.5, 0.1]])
drop_prob = 0.2

out, mask = dropout_forward(input_array= x,drop_prob = drop_prob)
print("Input x:")
print(x)
print("Random matrix:")
print("Output with dropout applied:")
print(out)
print("mask:")
print(mask)

Input x:
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.2 0.5 0.6]
 [0.4 0.3 0.6]
 [0.4 0.5 0.1]]
Random matrix:
Output with dropout applied:
[[0.125 0.    0.375]
 [0.    0.625 0.75 ]
 [0.25  0.    0.75 ]
 [0.5   0.375 0.75 ]
 [0.5   0.625 0.125]]
mask:
[[1.25 0.   1.25]
 [0.   1.25 1.25]
 [1.25 0.   1.25]
 [1.25 1.25 1.25]
 [1.25 1.25 1.25]]
